branch-defaults:
  8-Deploy_API:
    environment: eshop4-env
    group_suffix: null
global:
  application_name: eshop4
  branch: null
  default_ec2_keyname: eshop_ssh_ec2_access_keypair
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
