# Generated by Django 4.2.3 on 2023-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_country_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
